Practise15.06.19.date time
Vladkee/TrainingTask pull request #15
Opened 2019-07-08 18:43 UTC by Vladkee

2019-08-02 22:01 UTC, alekseybeletsky commented on TrainingTask/Task1Classes/IMyList.cs
> +
Please remove excessive empty line.

2019-08-02 22:01 UTC, alekseybeletsky commented on TrainingTask/Task1Classes/MyList.cs
> +			get {
Please align the code.

2019-08-02 22:02 UTC, alekseybeletsky commented on TrainingTask/Task1Classes/MyList.cs
> +				if (index > array.Length-1)
It is enough to index >= array.Length

2019-08-02 22:02 UTC, alekseybeletsky commented on TrainingTask/Task1Classes/MyList.cs
> +		protected T[] array;
The field should be private!

2019-08-02 22:03 UTC, alekseybeletsky commented on TrainingTask/Task1Classes/MyList.cs
> +			get { return array.Length; }
Missed 'this.' for instance members.

2019-08-02 22:03 UTC, alekseybeletsky commented on TrainingTask/Task1Classes/MyList.cs
> +			T[] array2 = new T[this.array.Length + 1];
Please give correct names.

2019-08-02 22:03 UTC, alekseybeletsky commented on TrainingTask/Task1Classes/MyList.cs
> +			{
Please follow to the only style - with brackets or not.

2019-08-02 22:03 UTC, alekseybeletsky commented on TrainingTask/Task1Classes/MyList.cs
> +			{
The same as above.

2019-08-02 22:04 UTC, alekseybeletsky commented on TrainingTask/Task2Classes/Car.cs
> +		public Car(string name, int year)
Please align the code.

2019-08-02 22:04 UTC, alekseybeletsky commented on TrainingTask/Task2Classes/Car.cs
> +		public string Name { get; set; }
Please separate class members with empty lines.

2019-08-02 22:04 UTC, alekseybeletsky commented on TrainingTask/Task2Classes/Car.cs
> +			return this.Name + " " + this.Year;
Please use string interpolation instead of concatenation.

2019-08-02 22:05 UTC, alekseybeletsky commented on TrainingTask/Task2Classes/CarCollection.cs
> +		private MyList<Car> carArray = new MyList<Car>();
Field should be initialized with default value in a constructor.

2019-08-02 22:05 UTC, alekseybeletsky commented on TrainingTask/Task2Classes/CarCollection.cs
> +		public void Management()
Should be in a separate class.

2019-08-02 22:06 UTC, alekseybeletsky commented on TrainingTask/Task2Classes/CarCollection.cs
> +		{
Incorrect logic.
The indexer should have been implemented here.

2019-08-02 22:07 UTC, alekseybeletsky requested changes
Please follow my comments.
The CarCollection does not have indexer.

2019-09-09 20:09 UTC, Vladkee commented
Task was reworked. String indexer is added.

2019-09-19 19:52 UTC, closed without merging